#!/usr/bin/env python3
"""
docker-debs-download.py

Downloads the latest available Docker Ubuntu .deb packages sequentially
from the Docker package repository.

The script:
- Scrapes the repository index page
- Detects all available versions for required packages
- Selects the latest version using semantic version sorting
- Downloads the latest package for each component
- Shows download progress
- Validates parameters before starting

Required dependency:
    pip install requests packaging

Usage:
    python3 download_docker_debs.py <download_folder>

Example:
    python3 download_docker_debs.py /tmp/docker-packages

Custom URL:
    python3 download_docker_debs.py /tmp/docker-packages \
        --url https://download.docker.com/linux/ubuntu/dists/resolute/pool/stable/amd64/

Author:
    Generated by ChatGPT
"""

import argparse
import os
import re
import sys
from pathlib import Path
from urllib.parse import urljoin

import requests
from packaging.version import Version

DEFAULT_BASE_URL = (
    "https://download.docker.com/linux/ubuntu/dists/resolute/pool/stable/amd64/"
)

PACKAGE_PATTERNS = {
    "containerd.io": (
        r"(containerd\.io_([0-9A-Za-z.+:~-]+)"
        r"~ubuntu\.26\.04~resolute_amd64\.deb)"
    ),
    "docker-buildx-plugin": (
        r"(docker-buildx-plugin_([0-9A-Za-z.+:~-]+)"
        r"~ubuntu\.26\.04~resolute_amd64\.deb)"
    ),
    "docker-ce-cli": (
        r"(docker-ce-cli_([0-9A-Za-z.+:~-]+)"
        r"~ubuntu\.26\.04~resolute_amd64\.deb)"
    ),
    "docker-ce": (
        r"(docker-ce_([0-9A-Za-z.+:~-]+)"
        r"~ubuntu\.26\.04~resolute_amd64\.deb)"
    ),
    "docker-compose-plugin": (
        r"(docker-compose-plugin_([0-9A-Za-z.+:~-]+)"
        r"~ubuntu\.26\.04~resolute_amd64\.deb)"
    ),
}

CHUNK_SIZE = 1024 * 1024  # 1 MB


def validate_url(url: str) -> str:
    """
    Validate URL parameter.
    """
    if not url.startswith(("http://", "https://")):
        raise argparse.ArgumentTypeError(
            f"Invalid URL '{url}'. Must start with http:// or https://"
        )

    if not url.endswith("/"):
        url += "/"

    return url


def validate_download_dir(path_str: str) -> Path:
    """
    Validate download directory.
    Create it if it does not exist.
    """
    path = Path(path_str).expanduser().resolve()

    if path.exists():
        if not path.is_dir():
            raise argparse.ArgumentTypeError(
                f"'{path}' exists but is not a directory"
            )
    else:
        try:
            path.mkdir(parents=True, exist_ok=True)
        except Exception as e:
            raise argparse.ArgumentTypeError(
                f"Cannot create directory '{path}': {e}"
            )

    if not os.access(path, os.W_OK):
        raise argparse.ArgumentTypeError(
            f"Directory '{path}' is not writable"
        )

    return path


def normalize_version(version_str: str) -> Version:
    """
    Convert Docker package versions into comparable semantic versions.

    Example:
        0.34.0-1  -> 0.34.0.post1
        0.34.0-2  -> 0.34.0.post2
        29.5.0-1  -> 29.5.0.post1
    """
    match = re.match(r"^([0-9][0-9A-Za-z.+]*)-(\d+)$", version_str)

    if match:
        base_version = match.group(1)
        revision = match.group(2)
        converted = f"{base_version}.post{revision}"
        return Version(converted)

    return Version(version_str)


def fetch_repository_listing(base_url: str) -> str:
    """
    Fetch repository HTML listing page.
    """
    print(f"Fetching repository index from:\n  {base_url}")

    try:
        response = requests.get(base_url, timeout=30)
        response.raise_for_status()
        return response.text

    except requests.exceptions.RequestException as e:
        raise RuntimeError(f"Failed to fetch repository listing: {e}")


def find_latest_package(html: str, package_name: str) -> str:
    """
    Find latest package filename from repository listing.
    """
    pattern = PACKAGE_PATTERNS[package_name]

    matches = re.findall(pattern, html)

    if not matches:
        raise RuntimeError(
            f"No matching packages found for '{package_name}'"
        )

    candidates = []

    for filename, version_str in matches:
        try:
            version = normalize_version(version_str)
            candidates.append((version, filename, version_str))
        except Exception:
            print(
                f"Skipping invalid version for {package_name}: "
                f"{version_str}"
            )

    if not candidates:
        raise RuntimeError(
            f"No valid versions found for '{package_name}'"
        )

    latest = max(candidates, key=lambda item: item[0])

    print(
        f"Latest {package_name}: "
        f"{latest[2]}"
    )

    return latest[1]


def format_size(size_bytes: int) -> str:
    """
    Convert bytes into human-readable format.
    """
    units = ["B", "KB", "MB", "GB", "TB"]
    size = float(size_bytes)

    for unit in units:
        if size < 1024 or unit == units[-1]:
            return f"{size:.1f} {unit}"
        size /= 1024


def print_progress(downloaded: int, total: int, filename: str):
    """
    Print progress bar.
    """
    if total > 0:
        percent = downloaded / total * 100

        bar_length = 40
        filled = int(bar_length * downloaded / total)

        bar = "#" * filled + "-" * (bar_length - filled)

        print(
            f"\r[{bar}] "
            f"{percent:6.2f}% "
            f"({format_size(downloaded)} / {format_size(total)}) "
            f"- {filename}",
            end="",
            flush=True,
        )
    else:
        print(
            f"\rDownloaded {format_size(downloaded)} - {filename}",
            end="",
            flush=True,
        )


def download_file(base_url: str, filename: str, output_dir: Path):
    """
    Download a single file sequentially.
    """
    url = urljoin(base_url, filename)

    output_path = output_dir / filename

    print(f"\nDownloading:\n  {filename}")

    try:
        with requests.get(url, stream=True, timeout=30) as response:
            response.raise_for_status()

            total_size = int(
                response.headers.get("content-length", 0)
            )

            downloaded = 0

            with open(output_path, "wb") as f:
                for chunk in response.iter_content(
                    chunk_size=CHUNK_SIZE
                ):
                    if chunk:
                        f.write(chunk)

                        downloaded += len(chunk)

                        print_progress(
                            downloaded,
                            total_size,
                            filename,
                        )

        print("\nDownload complete.")

    except requests.exceptions.RequestException as e:
        if output_path.exists():
            output_path.unlink(missing_ok=True)

        raise RuntimeError(
            f"Failed to download '{filename}': {e}"
        )


def parse_args():
    """
    Parse command-line arguments.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Download latest Docker Ubuntu .deb packages "
            "sequentially."
        )
    )

    parser.add_argument(
        "download_folder",
        type=validate_download_dir,
        help="Folder where files will be downloaded",
    )

    parser.add_argument(
        "--url",
        type=validate_url,
        default=DEFAULT_BASE_URL,
        help=f"Base repository URL (default: {DEFAULT_BASE_URL})",
    )

    return parser.parse_args()


def main():
    """
    Main script entry point.
    """
    try:
        args = parse_args()

        print("\nConfiguration")
        print("-------------")
        print(f"Download folder : {args.download_folder}")
        print(f"Repository URL  : {args.url}")

        html = fetch_repository_listing(args.url)

        print("\nResolving latest package versions...")
        print("------------------------------------")

        latest_files = []

        for package_name in PACKAGE_PATTERNS:
            latest_file = find_latest_package(
                html,
                package_name,
            )

            latest_files.append(latest_file)

        print("\nFiles to download")
        print("-----------------")

        for file in latest_files:
            print(f"  {file}")

        print("\nStarting downloads...")
        print("----------------------")

        for filename in latest_files:
            download_file(
                args.url,
                filename,
                args.download_folder,
            )

        print("\nAll downloads completed successfully.")

    except KeyboardInterrupt:
        print("\nInterrupted by user.")
        sys.exit(130)

    except Exception as e:
        print(f"\nError: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()